Support prometheus.remoteWrite flag
neticdk/k8s-oaas-observability pull request #238
Opened 2024-05-29 18:58 UTC by cthtrifork

2024-06-06 12:51 UTC, langecode requested changes
I am not quite sure what the use-case would be for this but I do think it looks ok - with the minor adjustments proposed.

2024-06-06 12:51 UTC, langecode commented on charts/oaas-observability/templates/prometheus/prometheus.yaml
>  {{- if or .Values.prometheus.prometheusSpec.containers .Values.prometheus.agent }}
```suggestion
{{- if or .Values.prometheus.prometheusSpec.containers .Values.prometheus.agent .Values.prometheus.remoteWrite }}
```

2024-06-06 12:51 UTC, langecode commented on charts/oaas-observability/Chart.yaml
> +version: 2.3.0
I think this would be ok to just qualify as patch version.

```suggestion
version: 2.2.1
```

2024-06-07 06:31 UTC, cthtrifork commented
> I am not quite sure what the use-case would be for this but I do think it looks ok - with the minor adjustments proposed.

The use case is to allow `remote_write`. We have some IoT agent which are not always running and we can not pull from. They should send/push the metrics to the `remote_write` endpoint. I have made an ingress that is bound to the specific url of the `remote_write` url of our prometheus instance + added basic auth to the ingress.

2024-06-07 06:34 UTC, cthtrifork commented
I had to rebase. Let me bump patch again

2024-06-07 08:14 UTC, langecode commented
> The use case is to allow `remote_write`. We have some IoT agent which are not always running and we can not pull from. They should send/push the metrics to the `remote_write` endpoint. I have made an ingress that is bound to the specific url of the `remote_write` url of our prometheus instance + added basic auth to the ingress.

I see no problem in making the chart here support setting up a remote write receiver. However, the "goto" solution for the use case you describe would normally be to set up a Prometheus [pushgateway](https://github.com/prometheus/pushgateway) - there is support for flushing data to push-gateway from multiple libraries, i.e., the .NET library for prometheus.

The remote write protocol by default allows you to push any sample directly into the tsdb of Prometheus - and you probably do not want a single IoT client to be able to mess with your data like that. What's even more in a setup at scale where Prometheus passes data to a central tsdb (like Cortex or VictoriaMetrics) the data ingested by remote write would by default be passed onto the central database.

The remote write protocol is designed for federation like if you want to pass Prometheus data into a central database. It was not designed to handle sampling of data from individual endpoints.

But we would be happy to accept the PR with the small changes suggested - the code changes looks quite ok.

2024-06-07 10:59 UTC, cthtrifork commented
> But we would be happy to accept the PR with the small changes suggested - the code changes looks quite ok.

Thanks for the links. It is good material. We are using a dedicated Prometheus per tenant and the clients are using grafana-agents for shipping metrics. So i think this solution can work for now, but we should look into pushgateway in the future.

I would like to get this PR merged :)

2024-06-10 05:11 UTC, langecode approved these changes

2024-06-10 05:11 UTC, merged